### ISSUE TITLE
Support for json file import

### ISSUE THREAD

**Issue by highcard** [samualtnorman/hackmud-script-manager#208]

**Comment by samualtnorman** [comment]
Fixed in d76d6688430f38da4f2c425aea5212dfd5e92422.

The next release to have this fix will be 0.21.

To receive the fix early:
- Run `npm install -g hackmud-script-manager@dev` if you have HSM installed globally
- Run `pnpm add hackmud-script-manager@dev` in the Hackmud Scripting Environment

You can import `.json` files like so:
```js
import myJson from "./path/to/my.json"

export default function () {
	return myJson
}
```
